<a href="https://colab.research.google.com/github/Rutuja-ctrl/rutuja/blob/main/7_One_Hot_Encoding%E2%80%8B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import Library**

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

**Import CSV as DataFrame**

In [ ]:
df=pd.read_csv(r'https://github.com/YBI-Foundation/Dataset/raw/main/Customer%20Purchase.csv')

**Get Information of DataFrame**

In [ ]:
df.head()

Customer ID  Age  Gender Education   Review Purchased
0         1021   30  Female    School  Average        No
1         1022   68  Female        UG     Poor        No
2         1023   70  Female        PG     Good        No
3         1024   72  Female        PG     Good        No
4         1025   16  Female        UG  Average        No

In [ ]:
df.shape

(50, 6)

In [ ]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Education', 'Review', 'Purchased'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Customer ID  50 non-null     int64 
 1   Age          50 non-null     int64 
 2   Gender       50 non-null     object
 3   Education    50 non-null     object
 4   Review       50 non-null     object
 5   Purchased    50 non-null     object
dtypes: int64(2), object(4)
memory usage: 2.5+ KB


**Get Features (X)Separated from DataFrame**

In [ ]:
X=df[['Age','Education','Review','Gender']]

In [ ]:
X

Age Education   Review  Gender
0    30    School  Average  Female
1    68        UG     Poor  Female
2    70        PG     Good  Female
3    72        PG     Good  Female
4    16        UG  Average  Female
5    31    School  Average  Female
6    18    School     Good    Male
7    60    School     Poor  Female
8    65        UG  Average  Female
9    74        UG     Good    Male
10   98        UG     Good  Female
11   74        UG     Good    Male
12   51    School     Poor    Male
13   57    School  Average  Female
14   15        PG     Poor    Male
15   75        UG     Poor    Male
16   59        UG     Poor    Male
17   22        UG     Poor  Female
18   19    School     Good    Male
19   97        PG     Poor    Male
20   57    School  Average  Female
21   32        PG  Average    Male
22   18        PG     Poor  Female
23   96    School     Good  Female
24   16        PG  Average  Female
25   57    School     Good  Female
26   53        PG     Poor  Female
27   69        PG     Poor  Female
28   48    School     Poor    Male
29   83        UG  Average  Female
30   73        UG  Average    Male
31   22    School     Poor  Female
32   92        UG  Average    Male
33   89        PG     Good  Female
34   86    School  Average    Male
35   74    School     Poor    Male
36   34        UG     Good  Female
37   94        PG  Average    Male
38   45    School     Good  Female
39   76        PG     Poor    Male
40   39    School     Good    Male
41   23        PG     Good    Male
42   30        PG     Good  Female
43   27        PG     Poor    Male
44   77        UG  Average  Female
45   61        PG     Poor    Male
46   64        PG     Poor  Female
47   38        PG     Good  Female
48   39        UG     Good  Female
49   25        UG     Good  Female

**Encode Categorical Features as an Integer Array**

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe=OneHotEncoder()

**As Example use One Hot Encoder on Individual Column to show the output**

In [ ]:
X_Gender = ohe.fit_transform(X[["Gender"]])

In [ ]:
ohe.categories_

[array(['Female', 'Male'], dtype=object)]

In [ ]:
X_Gender.toarray().shape

(50, 2)

In [ ]:
X_Gender.toarray()

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

**Two Dummy Variables ,each for Male and Female**

In [ ]:
X_Education = ohe.fit_transform(X[["Education"]])

In [ ]:
ohe.categories_

[array(['PG', 'School', 'UG'], dtype=object)]

In [ ]:
X_Education.toarray().shape

(50, 3)

In [ ]:
X_Education.toarray()

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

**Three Dummy Variables ,each for School,UG and PG**

In [ ]:
X_Review = ohe.fit_transform(X[["Review"]])

In [ ]:
ohe.categories_

[array(['Average', 'Good', 'Poor'], dtype=object)]

In [ ]:
X_Review.toarray().shape

(50, 3)

In [ ]:
X_Review.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1

**Create One Hot Encoder  (Dummy Variables)for All Features(X)**

In [ ]:
X = df[['Gender','Education','Review']]

In [ ]:
X = ohe.fit_transform(X)

In [ ]:
X.toarray().shape

(50, 8)

In [ ]:
X.toarray()

array([[1., 0., 0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 1., 0., 0.],
       [1., 0., 0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 

**Create one Hot Encoder (Dummy Variables) for All Features (X) as per choice**

In [ ]:
X = df[['Gender','Education','Review']]

In [ ]:
ohe = OneHotEncoder(categories=[['Male','Female'],['School','UG','PG'],['Poor','Average','Good']])

In [ ]:
X = ohe.fit_transform(X)

In [ ]:
X.toarray().shape

(50, 8)

In [ ]:
X.toarray()

array([[0., 1., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 1., 0., 0.],
       [1., 0., 0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 1., 0., 0.],
       [0., 1., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 1., 1., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 1.],
       [0., 1., 

**Reverse Encode Integer Array as categorical features(X)label**

In [ ]:
ohe.inverse_transform([[0.,1.,1.,0.,0.,0.,1.,0.]])

array([['Female', 'School', 'Average']], dtype=object)

**Drop First Dummy Variable From Each Categorical Features(X)to avoid multicolinearity**

**Specifies a methodology  to use to drop one of the categories per features.This is useful in situations where perfectly collinear feature cause problems.such as when feeding the resulting data into a neural network or an unregularized regression**

In [ ]:
X = df[['Gender','Education','Review']]

In [ ]:
ohe =  OneHotEncoder(drop='first')

In [ ]:
X = ohe.fit_transform(X)

In [ ]:
ohe.categories_

[array(['Female', 'Male'], dtype=object),
 array(['PG', 'School', 'UG'], dtype=object),
 array(['Average', 'Good', 'Poor'], dtype=object)]

In [ ]:
X.toarray().shape

(50, 5)

In [ ]:
X.toarray()

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0.],
       [0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [1., 0., 1., 1., 0.],
       [0., 0., 1., 1., 0.],
       [1., 0., 1., 1., 0.],
       [1., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1.],
       [0., 0., 1., 0., 1.],
       [1., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 1.